### ISSUE TITLE
Go build is failing in sample directory

### ISSUE THREAD

**Issue by hashir91** [johandry/terranova-examples#3]
$ make build
go build .
# github.com/johandry/terranova-examples/01_simple/simple
./main.go:24:46: terranova.NewPlatform(code).SetMiddleware undefined (type *terranova.Platform has no field or method SetMiddleware)
make: *** [build] Error 2

**Comment by hashir91** [comment]
To add I am using "go version go1.15.2"

**Comment by johandry** [comment]
This issue has been solved in PR #4 
Please, clone/pull the repository again and test, it should work.

This problems (and others) are caused by use of incorrect version in the `go.mod` file, after updating the version it works.

I'll make sure to update to the latest version every time there is a new Terranova release.
